on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: get dir name
    steps:
    - name: test qt
      run: |
        ls -la
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ls -la
 
