on:
  push:
    branches:
      - master
      - dev
      
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: hello
    steps:
      - uses: actions/checkout@v1
      - name: build
      - run: |
          echo "hello"
      
 
