on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: get dir name
    steps:
      - name: Hello world action step
        id: dirName
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'e0fe'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Current dir is ${{ steps.dirName.outputs.currentDir }}"
