on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: get dir name
    steps:
      - name: Hello world action step
        id: dirName
        uses: actions/DockerContainer@master
        with:
          build_type: 'Release'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Current dir is ${{ steps.dirName.outputs.currentDir }}"
