on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: get dir name
    steps:
    - uses: actions/checkout@v2
    - name: test qt
      run: |
        ls -la && mkdir build && ls -la && cd build && cmake .. && cmake --build . && ls -la
 
